apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-sql-db-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-sql
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-sql-db.git
      sourceType: git
  ui:
    input: {}
